baseURL: "https://wyq977.github.io/"
languageCode: "en-us"
title: "Yongqi Wang"
theme: "bw-minimal"

pagination:
  pagerSize: 999

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - ["$$", "$$"]
            - ['\\[', '\\]']
          inline:
            - ["$", "$"]
            - ['\\(', '\\)']
  highlight:
    style: "friendly"        # "tango" is a nice light theme. Others: "trac", "manni", "friendly"
    # noClasses: false      # This forces Hugo to inject the colors directly (easier for you)

params:
  math: true
  mainSections:
    - post

  footer:
    since: 2019
    customText: "Personal Web pages of CWI staff do not in any way constitute official CWI content. The views and opinions expressed in individual's Web pages are strictly those of the page authors. Comments on the contents of those pages should be directed to the page authors"

  dateFormat: "2006-05-28"

# # Simple URL structure: baseurl/blog/my-post-title/
# permalinks:
#   post: /:slug/

disableKinds:
  - "taxonomy"
  - "term"


# ADD THIS SECTION BELOW GOLDMARK

